[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path = 'cache'

solc = "0.8.23"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
build_info = true
extra_output = ["storageLayout"]
ffi = true
ast = true

[rpc_endpoints]
bArtio = "https://bartio.rpc.berachain.com/"

[etherscan]
bArtio = { key = "verifyContract", url = "https://api.routescan.io/v2/network/testnet/evm/80084/etherscan", chain = 80084 }